CMDs := DSPALT.CMD
DSPFs := FMDDSPALTD.FILE
MODULEs := FMRDSPALTD.MODULE
PGMs := FMRDSPALTD.PGM
PNLGRPs := FMHDSPALT.PNLGRP

DSPALT.CMD: DSPALT.CMDSRC
DSPALT.CMD: private PGM := FMRALTSND
DSPALT.CMD: private HLPPNLGRP := FMHDSPALT
FMDDSPALTD.FILE: FMDDSPALTD.DSPF
FMRDSPALTD.MODULE: FMRDSPALTD.SQLRPGLE FMDDSPALTD.FILE
FMRDSPALTD.PGM: FMRDSPALTD.ILEPGM FMRDSPALTD.MODULE
FMHDSPALT.PNLGRP: FMHDSPALT.PNLGRPSRC
